/*
 * dclk_init.c
 *
 *  Created on: 10 Jan 2026
 *      Author: katog
 */


#include "dclk_init.h"
/* I2C BUS INIT */
/**
 * @brief Initializing function for the I2C bus responsible for communication to ds1307 and sh1106. Executes inside vTaskDCLKInit
 * @param I2C_HANDLE: I2C bus handle for I2C configurations
 */
void I2C_DCLK_BUS_INIT(I2C_Handle_t* I2C_HANDLE)
{
	I2C_HANDLE->DEVICE_ADDR 			= 0x69;
	I2C_HANDLE->I2C_SPD 				= I2C_SPEED_SM;
	I2C_HANDLE->I2C_FM_DUTY_MODE 	= I2C_FM_DUTY_MODE_2;
	I2C_HANDLE->pI2Cx 				= I2C1;
	I2C_HANDLE->I2C_STATUS 			= I2C_STATUS_READY;
	I2C_INIT(I2C_HANDLE);
}
/* I2C PINS INIT */
/**
 * @brief Initializing function responsible for GPIO configuration of the I2C bus. Executes inside vTaskDCLKInit.
 * @param GPIO_I2C_HANDLE: GPIO handle for the I2C bus
 */
void I2C_DCLK_BUS_GPIO_INIT(GPIO_Handle_t* GPIO_I2C_HANDLE)
{
	GPIO_I2C_HANDLE->GPIO_AFIO_MODE 		= AFIO_MODE_4;
	GPIO_I2C_HANDLE->GPIO_MODE 			= GPIO_PIN_MODE_AFIO;
	GPIO_I2C_HANDLE->GPIO_OUTPUT_SPD 	= GPIO_OUT_FST_SPD;
	GPIO_I2C_HANDLE->GPIO_OUTPUT_TYPE 	= GPIO_OUT_OD;
	GPIO_I2C_HANDLE->GPIO_PUPPD 			= GPIO_NO_PUPD;
	GPIO_I2C_HANDLE->pGPIOx 				= GPIOB;

	// PB8 SCL
	GPIO_I2C_HANDLE->GPIO_PIN_NUMBER 	= GPIO_PIN_NUMBER_8;
	GPIO_INIT(GPIO_I2C_HANDLE);

	// PB9 SDA
	GPIO_I2C_HANDLE->GPIO_PIN_NUMBER 	= GPIO_PIN_NUMBER_9;
	GPIO_INIT(GPIO_I2C_HANDLE);
}

/* DHT22 PIN INIT */
/**
 * @brief
 * @param
 */
void DIGILOCK_DHT22_PIN_INITS( GPIO_Handle_t* DHT22_GPIO_HANDLE )
{
	DHT22_GPIO_HANDLE->GPIO_MODE 		= GPIO_PIN_MODE_INPUT;
	DHT22_GPIO_HANDLE->GPIO_PUPPD		= GPIO_NO_PUPD;
	DHT22_GPIO_HANDLE->GPIO_OUTPUT_TYPE = GPIO_OUT_PP;
	DHT22_GPIO_HANDLE->GPIO_OUTPUT_SPD	= GPIO_OUT_FST_SPD;
	DHT22_GPIO_HANDLE->pGPIOx 			= GPIOC;
	DHT22_GPIO_HANDLE->GPIO_PIN_NUMBER	= GPIO_PIN_NUMBER_9;

	GPIO_INIT( DHT22_GPIO_HANDLE );
}

/* GPIO BUTTONS INIT */
/**
 * @brief
 * @param
 */
void DCLK_BUTTON_PINS_INIT()
{
	GPIO_Handle_t DCLK_BTTNS;
	// increment and confirm buttons
	DCLK_BTTNS.GPIO_MODE = GPIO_PIN_MODE_INPUT;
	DCLK_BTTNS.GPIO_PUPPD = GPIO_PULL_UP;
	DCLK_BTTNS.pGPIOx = GPIOB;
	DCLK_BTTNS.EXTI_CFG.EXTI_EMR_SET = DISABLE;
	DCLK_BTTNS.EXTI_CFG.EXTI_IMR_SET = ENABLE;
	DCLK_BTTNS.EXTI_CFG.EXTI_FTSR_SEL = ENABLE;
	DCLK_BTTNS.EXTI_CFG.EXTI_RTSR_SEL = DISABLE;

	// EXTI to enter vTaskSetDate task
	DCLK_BTTNS.GPIO_PIN_NUMBER = GPIO_PIN_NUMBER_1;
	GPIO_INIT(&DCLK_BTTNS);

	// EXTI to enter vTaskSetTime task
	DCLK_BTTNS.GPIO_PIN_NUMBER = GPIO_PIN_NUMBER_2;
	GPIO_INIT(&DCLK_BTTNS);
	/*EXTI[0].IMR &= ~(1 << GPIO_PIN_NUMBER_2);*/

	// EXTI for increment
	DCLK_BTTNS.GPIO_PIN_NUMBER = GPIO_PIN_NUMBER_3;
	GPIO_INIT(&DCLK_BTTNS);

	// EXTI for confirm button
	DCLK_BTTNS.GPIO_PIN_NUMBER = GPIO_PIN_NUMBER_15;
	GPIO_INIT(&DCLK_BTTNS);

}

